USE ROLE ACCOUNTADMIN;

CREATE STORAGE INTEGRATION IF NOT EXISTS STREAMIFY_AZURE_INT
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'AZURE'
  ENABLED = TRUE
  AZURE_TENANT_ID = '<azure-tenant-id>'
  STORAGE_ALLOWED_LOCATIONS = (
    'azure://<storage-account-name>.blob.core.windows.net/streamify/'
  );

-- Run this now. Use AZURE_CONSENT_URL and AZURE_MULTI_TENANT_APP_NAME to
-- complete the Azure consent and IAM steps described in snowflake_setup.md.
DESC STORAGE INTEGRATION STREAMIFY_AZURE_INT;

GRANT USAGE ON INTEGRATION STREAMIFY_AZURE_INT
  TO ROLE STREAMIFY_TRANSFORMER;

USE DATABASE STREAMIFY;
USE SCHEMA STREAMIFY_STG;

CREATE FILE FORMAT IF NOT EXISTS STREAMIFY_PARQUET_FORMAT
  TYPE = PARQUET;

CREATE STAGE IF NOT EXISTS STREAMIFY_ADLS_STAGE
  URL = 'azure://<storage-account-name>.blob.core.windows.net/streamify/'
  STORAGE_INTEGRATION = STREAMIFY_AZURE_INT
  FILE_FORMAT = STREAMIFY_PARQUET_FORMAT;

GRANT USAGE ON FILE FORMAT STREAMIFY_PARQUET_FORMAT
  TO ROLE STREAMIFY_TRANSFORMER;
GRANT USAGE ON STAGE STREAMIFY_ADLS_STAGE
  TO ROLE STREAMIFY_TRANSFORMER;

-- Verify Snowflake can see the Parquet files after Azure IAM is configured.
LIST @STREAMIFY_ADLS_STAGE/listen_events/;
