USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS STREAMIFY_TRANSFORMER;

CREATE WAREHOUSE IF NOT EXISTS STREAMIFY_TRANSFORM_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS STREAMIFY;
CREATE SCHEMA IF NOT EXISTS STREAMIFY.STREAMIFY_STG;
CREATE SCHEMA IF NOT EXISTS STREAMIFY.STREAMIFY_PROD;

CREATE USER IF NOT EXISTS STREAMIFY_DBT
  TYPE = SERVICE
  DEFAULT_ROLE = STREAMIFY_TRANSFORMER
  DEFAULT_WAREHOUSE = STREAMIFY_TRANSFORM_WH
  DEFAULT_NAMESPACE = STREAMIFY.STREAMIFY_STG
  COMMENT = 'Service user for Streamify dbt';

GRANT ROLE STREAMIFY_TRANSFORMER TO USER STREAMIFY_DBT;
GRANT USAGE ON WAREHOUSE STREAMIFY_TRANSFORM_WH TO ROLE STREAMIFY_TRANSFORMER;
GRANT USAGE ON DATABASE STREAMIFY TO ROLE STREAMIFY_TRANSFORMER;

GRANT USAGE, CREATE TABLE, CREATE VIEW
  ON SCHEMA STREAMIFY.STREAMIFY_STG
  TO ROLE STREAMIFY_TRANSFORMER;
GRANT USAGE, CREATE TABLE, CREATE VIEW
  ON SCHEMA STREAMIFY.STREAMIFY_PROD
  TO ROLE STREAMIFY_TRANSFORMER;

GRANT SELECT ON ALL TABLES IN SCHEMA STREAMIFY.STREAMIFY_STG
  TO ROLE STREAMIFY_TRANSFORMER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA STREAMIFY.STREAMIFY_STG
  TO ROLE STREAMIFY_TRANSFORMER;

-- Replace the placeholder with the single-line public-key body generated on
-- the Airflow VM. Do not paste the BEGIN/END PUBLIC KEY lines.
ALTER USER STREAMIFY_DBT ADD KEY PAIR STREAMIFY_DBT_KEY
  PUBLIC_KEY = '<snowflake-public-key-body>'
  ROLE_RESTRICTION = 'STREAMIFY_TRANSFORMER';
