COPY INTO STREAMIFY.STREAMIFY_STG.PAGE_VIEW_EVENTS
FROM @STREAMIFY.STREAMIFY_STG.STREAMIFY_ADLS_STAGE/page_view_events/
FILE_FORMAT = (FORMAT_NAME = STREAMIFY.STREAMIFY_STG.STREAMIFY_PARQUET_FORMAT)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
PATTERN = '.*[.]parquet'
ON_ERROR = 'ABORT_STATEMENT';
